### PR TITLE
chore: update screenshots

### LINKED ISSUE #258: enhancement: update screenshots
[README screenshots](https://github.com/gokarna-theme/gokarna-hugo?tab=readme-ov-file#screenshots) are out of date:

- Copyright year (`now.Year`) is 2023
- [x] Update Home page screenshot
- [x] Update Posts page screenshot
  Home page and Posts page need yearly updates.
- [x] Update Documentation - Basics screenshot (#243, #233)
- ~~Replace Performance (Google Lighthouse) screenshot with higher resolution~~ Wait for #250 (#260, #261)

Low priority and good first issue.

### PR DESCRIPTION
**Pull request by jamesericdavidson**
Closes #258. @526avijitgupta

### CODE REVIEW

**Comment by yashmehrotra** [comment]
@jamesericdavidson Weird that the padding b/w the top bar has changed in the screenshots, do you recall if we made any changes for those ? 

cc @526avijitgupta

**Comment by jamesericdavidson** [comment]
May be a consequence of running the latest Firefox version available in Alpine (e.g. changes to Firefox, Linux rendering differences from Mac, etc.), but more likely it's changes in Gokarna.

We can checkout the last commit and compare - or git blame? @yashmehrotra

**Comment by 526avijitgupta** [comment]
@yashmehrotra Yes you're right the padding has increased. But to be fair the screenshots in README are 3 years old, and we've had a lot of changes since then:

image

And the new layout still looks good to me. I would say let's keep it as is. What do you think?

**Review by 526avijitgupta — APPROVED** [review]
lgtm. Let's wait for @yashmehrotra 's review

**Comment by yashmehrotra** [comment]
@526avijitgupta Cool, merging then

**Pull request merged**
