### PR TITLE
refactor: pass lighthouse SEO audits

### LINKED ISSUE #259: Improving Google Lighthouse SEO score
https://github.com/gokarna-theme/gokarna-hugo/issues/250 talks about improving performance based on Google lighthouse score. Reviewing the [lightscore score](https://pagespeed.web.dev/analysis/https-gokarna-hugo-netlify-app/w90db0qrkg?form_factor=desktop), there's a scope of improving SEO to improve our visibility as a theme. 

image

image

cc @jamesericdavidson

### PR DESCRIPTION
**Pull request by jamesericdavidson**
Closes #259 

- [x] theme toggle
- [x] `sr-only` theme toggle
- [x] `sr-only` hamburger menu
- ~~structured data validator~~ needs account

### CODE REVIEW

**Comment by jamesericdavidson** [comment]
@526avijitgupta Passes locally on mobile and desktop tests

image

**Comment by 526avijitgupta** [comment]
I have just re-enabled deploy previews from Netlify in the repository. Deploy previews had stopped working when we moved the repo to an organization I guess.
cc @yashmehrotra 

@jamesericdavidson Could you please push an empty commit to trigger the deploy preview in this PR?

**Comment by yashmehrotra** [comment]
@526avijitgupta Thanks for fixing deploy previews

Can we merge this PR?

**Comment by 526avijitgupta** [comment]
I tested it locally, looks fine. Thanks @jamesericdavidson 🙌 merging

**Pull request merged**
